---

- name: "System deps for protobuf"
  become: yes
  apt:
    name:
    - autoconf
    - automake
    - libtool
    - curl
    - make
    - unzip
    - zlib1g-dev

- name: "Check if protobuf installed"
  stat:
    path: /usr/local/lib/libprotobuf.so
  register: pb_stat

- name: "Clone Protobuf"
  git:
    repo: "https://github.com/protocolbuffers/protobuf.git"
    dest: "/tmp/protobuf"
    version: "v3.12.4"
  when: pb_stat.stat.exists == False

- name: "Set up build"
  shell: "mkdir -p build"
  args:
    chdir: "/tmp/protobuf/cmake"
  when: pb_stat.stat.exists == False

# Note - compiling with clang avoids excessing warnings
- name: "Configure protobuf"
  shell: >
    cmake -GNinja
    -Dprotobuf_BUILD_SHARED_LIBS=ON
    -Dprotobuf_BUILD_TESTS=OFF
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10
    -DCMAKE_C_COMPILER=/usr/bin/clang-10
    -DCMAKE_BUILD_TYPE=Release ..
  args:
    chdir: "/tmp/protobuf/cmake/build"
  when: pb_stat.stat.exists == False

- name: "Build protobuf"
  shell: "ninja"
  args:
    chdir: "/tmp/protobuf/cmake/build"
  when: pb_stat.stat.exists == False

- name: "Install"
  become: yes
  shell: "ninja install"
  args:
    chdir: "/tmp/protobuf/cmake/build"
  when: pb_stat.stat.exists == False
