---

- name: "Clone musl"
  git:
    repo: 'git://git.musl-libc.org/musl'
    dest: /usr/local/code/musl_native
    version: v1.1.24

- name: "Build"
  shell: "{{ item }}"
  args:
    chdir: "/usr/local/code/musl_native"
  with_items:
    - "CC=/usr/bin/clang ./configure --prefix=/usr/local/faasm/musl_native"
    - "make -j 10"

- name: "Install"
  become: yes
  shell: "{{ item }}"
  args:
    chdir: "/usr/local/code/musl_native"
  with_items:
    - "mkdir -p /usr/local/faasm/musl_native"
    - "sudo make install"


