version: "3"

services:
  redis:
    image: faasm/redis:latest
    ports:
      - "6377:6379"

  tester:
    image: faasm/testing:latest
    depends_on:
      - redis
    environment:
      HOST_TYPE: "ci"
      CGROUP_MODE: "on"
      REDIS_STATE_HOST: "redis"
      REDIS_QUEUE_HOST: "redis"
      THREADS_PER_WORKER: 5
      LOG_LEVEL: debug
    volumes:
      - .:/usr/local/code/faasm
    privileged: yes
