version: "3"

services:
  redis:
    image: faasm/redis:${FAASM_VERSION}
    ports:
      - "6377:6379"

  tester:
    image: faasm/testing:${FAASM_VERSION}
    depends_on:
      - redis
    environment:
      HOST_TYPE: "ci"
      CGROUP_MODE: "on"
      REDIS_STATE_HOST: "redis"
      REDIS_QUEUE_HOST: "redis"
      THREADS_PER_WORKER: 5
      LOG_LEVEL: info
    volumes:
      - .:/usr/local/code/faasm
    privileged: yes
