version: "3"

services:
  ibm-worker-1:
    image: faasm/ibm-worker:0.1.1
    env_file:
      - docker-compose-ibm.env
    ports:
      - "8081:8080"
    privileged: yes

  upload:
    image: faasm/upload
    ports:
      - "8002:8002"
    env_file:
      - docker-compose-ibm.env
    volumes:
      - /usr/local/faasm/:/usr/local/faasm/
      - /usr/local/code/faasm/wasm/:/usr/local/code/faasm/wasm/
