version: "3"

networks:
  faasm-knative:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  redis-state:
    image: redis:5
    ports:
      - "6378:6379"
    networks:
      - faasm-knative

  redis-queue:
    image: redis:5
    ports:
      - "6377:6379"
    networks:
      - faasm-knative

  knative-worker-1:
    image: faasm/knative-worker:latest
    depends_on:
      - redis-queue
      - redis-state
    env_file:
      - docker-compose.env
    ports:
      - "8081:8080"
    privileged: yes
    networks:
      faasm-knative:
        ipv4_address: 172.28.1.2

  knative-worker-2:
    image: faasm/knative-worker:latest
    depends_on:
      - redis-queue
      - redis-state
    env_file:
      - docker-compose.env
    ports:
      - "8082:8080"
    privileged: yes
    networks:
      faasm-knative:
        ipv4_address: 172.28.1.3

  proxy:
    build:
      context: .
      dockerfile: docker/local-proxy.dockerfile
    depends_on:
      - knative-worker-1
      - knative-worker-2
    ports:
      - "8080:8080"
    networks:
      faasm-knative:
        ipv4_address: 172.28.1.1

  upload:
    image: faasm/upload:latest
    ports:
      - "8002:8002"
    depends_on:
      - redis-queue
      - redis-state
    env_file:
      - docker-compose.env
    networks:
      - faasm-knative
    volumes:
      - /usr/share/faasm/wasm:/usr/share/faasm/wasm
