---

apiVersion: v1
kind: Pod
metadata:
  name: planner
  namespace: faasm
  labels:
    app: faasm
    role: planner
spec:
  containers:
    - name: planner
      image: faasm.azurecr.io/planner:0.4.3
      ports:
        - containerPort: 8081
      env:
        - name: LOG_LEVEL
          value: "info"
