---

apiVersion: v1
kind: Pod
metadata:
  name: redis-queue
  namespace: faasm
  labels:
    app: faasm
    role: redis-queue
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: faasm.io/role
            operator: In
            values:
            - control
  containers:
    - name: master
      image: faasm.azurecr.io/redis:0.23.1
      ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Pod
metadata:
  name: redis-state
  namespace: faasm
  labels:
    app: faasm
    role: redis-state
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: faasm.io/role
            operator: In
            values:
            - control
  containers:
    - name: master
      image: faasm.azurecr.io/redis:0.23.1
      ports:
        - containerPort: 6379

---

# Allow redis services to be accessed by other pods
apiVersion: v1
kind: Service
metadata:
  name: redis-queue
  namespace: faasm
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    role: redis-queue

---

apiVersion: v1
kind: Service
metadata:
  name: redis-state
  namespace: faasm
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    role: redis-state
