---

- name: "Check if arrow installed"
  stat:
    path: /usr/include/arrow
  register: a_stat

- name: "Download Arrow deb file"
  get_url:
    url: "http://apache.bintray.com/arrow/{{ ansible_distribution|lower }}/apache-arrow-archive-keyring-latest-{{ ansible_distribution_release }}.deb"
    dest: "/tmp/arrow.deb"
  when: a_stat.stat.exists == False

- name: "Set up Arrow"
  become: yes
  shell: "{{ item }}"
  with_items:
    - "apt install -y -V /tmp/arrow.deb"
    - "apt update"
    - "apt install -y libarrow-dev libarrow-flight-dev"
  when: a_stat.stat.exists == False
