---

- name: "Remove existing cmake"
  become: yes
  shell: "apt remove --purge cmake -y"

- name: "Download cmake script"
  get_url:
    url: https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.sh
    dest: /tmp/cmake-linux.sh
    mode: 755

- name: "Run cmake install"
  become: yes
  shell: "sh cmake-linux.sh -- --skip-license --prefix=/usr/local"
  args:
    chdir: "/tmp"

