---

- name: "Download file"
  get_url:
    url: https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz
    dest: /tmp/cmake-3.16.5.tar.gz

- name: "Extract"
  shell: "tar -zxvf cmake-3.16.5.tar.gz"
  args:
    chdir: /tmp

- name: "Set up"
  shell: "{{ item }}"
  args:
    chdir: /tmp/cmake-3.16.5
  with_items:
    - "./bootstrap"
    - "make"

- name: "Install"
  become: yes
  shell: "make install"
  args:
    chdir: /tmp/cmake-3.16.5