apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  namespace: knative-serving
data:
  # Node selection
  kubernetes.podspec-affinity: "enabled"
  kubernetes.podspec-nodeselector: "enabled"

