---

- name: "Ensure base faasm local dir exists"
  become: yes
  file:
    path: "/usr/local/faasm"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775

- name: "Ensure runtime_root directory exists"
  file:
    path: "/usr/local/faasm/runtime_root/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775
  with_items:
    - "etc"
    - "tmp"
    - "share"

- name: "Put network-related files in place"
  copy:
    src: "{{ item }}"
    dest: "/usr/local/faasm/runtime_root/etc/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items:
    - "hosts"
    - "resolv.conf"
    - "passwd"

