---

- name: "Check if emsdk already installed"
  stat:
    path: /usr/local/faasm/emsdk
  register: dir_stat

- name: "Ensure directory"
  become: yes
  file:
    path: "/usr/local/faasm"
    state: directory
    mode: 0777
  when: dir_stat.stat.exists == False

- name: "Download TAR"
  shell: "{{ item }}"
  args:
    chdir: "/usr/local/faasm"
  with_items:
    - "wget https://s3-eu-west-1.amazonaws.com/faasm-misc/emsdk.tar.gz -O emsdk.tar.gz"
    - "tar -xf emsdk.tar.gz"
    - "rm emsdk.tar.gz"
  when: dir_stat.stat.exists == False