#include <conf/FaasmConfig.h>
#include <enclave/outside/attestation/AttestationServiceClient.h>
#include <enclave/outside/attestation/attestation.h>
#include <enclave/outside/ecalls.h>
#include <faabric/util/logging.h>

#ifdef FAASM_SGX_HARDWARE_MODE
#include <dlfcn.h>
#include <openssl/evp.h>
#include <sgx_dcap_ql_wrapper.h>
#include <sgx_ql_lib_common.h>
#include <sgx_report.h>
#include <sgx_urts.h>
#endif

namespace sgx {

#ifdef FAASM_SGX_HARDWARE_MODE
static void sha256sum(const uint8_t* data, uint32_t data_size, uint8_t* hash)
{
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    EVP_DigestInit_ex(ctx, EVP_sha256(), NULL);
    EVP_DigestUpdate(ctx, data, data_size);
    EVP_DigestFinal_ex(ctx, hash, &data_size);
    EVP_MD_CTX_free(ctx);
}

sgx_target_info_t getQuotingEnclaveTargetInfo()
{
    sgx_target_info_t targetInfo;
    quote3_error_t qeReturnValue = sgx_qe_get_target_info(&targetInfo);

    if (qeReturnValue != SGX_QL_SUCCESS) {
        SPDLOG_ERROR("Error getting the quoting enclave's info: 0x{:04X}",
                     qeReturnValue);
        throw std::runtime_error("Error getting the QE's info");
    }

    return targetInfo;
}

/* This method takes an SGX report generated by a Faaslet running in an SGX
 * enclave and converts it to an SGX quote by requeting a signature from the
 * quoting enclave.
 */
std::vector<uint8_t> getQuoteFromReport(sgx_report_t enclaveReport)
{
    uint32_t quoteSize = 0;
    quote3_error_t qeReturnValue = sgx_qe_get_quote_size(&quoteSize);
    if (qeReturnValue != SGX_QL_SUCCESS) {
        SPDLOG_ERROR("Error getting enclave'squote size: 0x{:04X}",
                     qeReturnValue);
        throw std::runtime_error("Error getting enclave's quote size");
    }

    std::vector<uint8_t> quoteBuffer(quoteSize, 0);
    qeReturnValue =
      sgx_qe_get_quote(&enclaveReport, quoteSize, quoteBuffer.data());
    if (qeReturnValue != SGX_QL_SUCCESS) {
        SPDLOG_ERROR("Error in getting enclave's quote: 0x{:04X}",
                     qeReturnValue);
        throw std::runtime_error("Error getting enclave's quote");
    }

    return quoteBuffer;
}
#endif
}
