version: 2
jobs:
  cpp_tests:
    docker:
      - image: faasm/testing
        environment:
          HOST_TYPE: ci
          CGROUP_MODE: "off"
          LOG_LEVEL: "debug"
      - image: redis

    working_directory: /usr/local/code/faasm

    steps:
      - checkout
      - run:
          name: "Sync submodules"
          command: git submodule sync
      - run:
          name: "Update submodules"
          command: git submodule update --init
      - run:
          name: "Set up and build"
          command: ./bin/ci_setup.sh
      - run:
          name: "Execute tests"
          command: /faasm/build/bin/tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp_tests:
          filters:
            branches:
              only:
                - circle2
                - master
