version: 2
jobs:
  cpp_tests:
    docker:
      - image: faasm/testing
        environment:
          THREADS_PER_WORKER=1
      - image: redis

    working_directory: /usr/local/code/faasm

    steps:
      - checkout
      - run:
          name: "Sync submodules"
          command: git submodule sync
      - run:
          name: "Update submodules"
          command: git submodule update --init
      - run:
          name: "Configure out of source build"
          command: cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_BUILD_TYPE=Release /usr/local/code/faasm
          working_dir: /faasm/build
      - run:
          name: "Build codegen"
          command: cmake --build . --target codegen
          working_dir: /faasm/build
      - run:
          name: "Run codegen on wasm files"
          command: ./bin/codegen /usr/local/code/faasm/wasm
          working_dir: /faasm/build
      - run:
          name: "Build tests"
          command: cmake --build . --target tests
          working_dir: /faasm/build
      - run:
          name: "Execute tests"
          command: ./bin/tests
          working_dir: /faasm/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp_tests
