version: 2
jobs:
  cpp_tests:
    docker:
      - image: faasm/testing
        environment:
          THREADS_PER_WORKER=1
      - image: redis

    working_directory: /faasm/build

    steps:
      - checkout
      - run:
          name: "Sync submodules"
          command: git submodule sync
          working_dir: /usr/local/code/faasm
      - run:
          name: "Update submodules"
          command: git submodule update --init
          working_dir: /usr/local/code/faasm
      - run:
          name: "Configure project"
          command: cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_BUILD_TYPE=Release /usr/local/code/faasm
      - run:
          name: "Build tests"
          command: cmake --build . --target tests
      - run:
          name: "Execute tests"
          command: ./bin/tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp_tests
