version: 2
jobs:
  cpp_tests:
    docker:
      - image: faasm/testing
        environment:
          THREADS_PER_WORKER=1

    working_directory: /usr/local/code/faasm

    steps:
      - checkout
      - run:
          name: "Sync submodules"
          command: git submodule sync
      - run:
          name: "Update submodules"
          command: git submodule update --init
      - run:
          name: "Set up build dir"
          command: mkdir /usr/local/code/faasm/build
      - run:
          name: "Configure project"
          command: cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_BUILD_TYPE=Release /usr/local/code/faasm
          working_dir: /usr/local/code/faasm/build
      - run:
          name: "Build tests"
          command: cmake --build . --target tests
          working_dir: /usr/local/code/faasm/build
      - run:
          name: "Execute tests"
          command: /usr/local/code/faasm/build/bin/tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp_tests
