version: 2
jobs:
  cpp_tests:
    docker:
      - image: faasm/testing
        environment:
          THREADS_PER_WORKER=1

    working_directory: /usr/local/code/faasm

    steps:
      - checkout
      - run:
          name: "Sync submodules"
          command: git submodule sync
      - run:
          name: "Update submodules"
          command: git submodule update --init
      - run:
          name: "Set up cgroups"
          command: ./bin/cgroup.sh
      - run:
          name: "Setting up namespaces"
          command: ./bin/netns.sh 2
      - run:
          name: "Build tests"
          command: mkdir build && cd build && cmake --build . --target tests
      - run:
          name: "Execute tests"
          command: /usr/local/code/faasm/build/bin/tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - cpp_tests
