---

- name: "Create Lambda IAM role"
  iam_role:
    name: "faasm-lambda-role"
    region: "{{ aws_region }}"
    state: present
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    managed_policy:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
