---

- name: "Check if cereal installed"
  stat:
    path: /usr/local/include/cereal
  register: c_stat

- name: "Download the cereal release"
  shell: "{{ item }}"
  args:
    chdir: "/tmp"
  with_items:
    - "wget https://github.com/USCiLab/cereal/archive/v1.3.0.tar.gz"
    - "tar -xf v1.3.0.tar.gz"
  when: c_stat.stat.exists == False

- name: "Put headers in place"
  become: yes
  shell: "cp -r include/cereal /usr/local/include"
  args:
    chdir: "/tmp/cereal-1.3.0"
  when: c_stat.stat.exists == False

- name: "Clean up"
  become: yes
  file:
    state: absent
    path: "/tmp/cereal-1.3.0"