apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faasm
      role: edge
  template:
    metadata:
      labels:
        app: faasm
        role: edge
    spec:
      containers:
        - name: edge
          image: faasm/edge
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: faasm-config
          volumeMounts:
            - mountPath: "/usr/share/faasm"
              name: func-vol
      nodeSelector:
        nodeRole: worker
      volumes:
        - name: func-vol
          persistentVolumeClaim:
            claimName: func-storage-claim
