apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faasm
      role: edge
  template:
    metadata:
      labels:
        app: faasm
        role: edge
    spec:
      containers:
        - name: edge
          image: faasm/edge
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: faasm-config
          volumeMounts:
            - mountPath: "/usr/share/faasm"
              name: func-vol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodeRole
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - worker
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: func-vol
          persistentVolumeClaim:
            claimName: func-storage-claim
