apiVersion: v1
kind: Pod
metadata:
  name: upload
  namespace: faasm
  labels:
    app: faasm
    role: upload
spec:
  containers:
    - name: upload
      image: faasm/upload
      imagePullPolicy: Always
      ports:
        - containerPort: 8002
      envFrom:
        - configMapRef:
            name: faasm-config
      volumeMounts:
        - mountPath: "/usr/share/faasm"
          name: func-vol
  volumes:
    - name: func-vol
      persistentVolumeClaim:
        claimName: func-storage-claim

