---

s3_bucket_name: "faasm-runtime"
sqs_queue_name: "faasm-messages"
elasticache_name: "faasm-redis"

aws_region: "eu-west-1"
aws_account_id: "733781933474"
aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=faasm file=~/.aws/credentials') }}"
aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=faasm file=~/.aws/credentials') }}"

private_key_name: "faasm_key"
private_key_file: "~/faasm_aws_key.pem"