---

vpc_name: "faasm-vpc"
public_subnet_name: "faasm-public"
private_subnet_name: "faasm-private"
internet_gateway_name: "faasm-igw"
nat_gateway_name: "faasm-nat"
lambda_role_name: "faasm-lambda-role"

vpc_cidr: "10.10.0.0/16"
public_subnet_cidr: "10.10.10.0/24"
private_subnet_cidr: "10.10.20.0/24"

s3_runtime_bucket: "faasm-runtime"
s3_state_bucket: "faasm-state"
sqs_queue_name: "faasm-messages"
elasticache_name: "faasm-redis"
security_group_name: "faasm-sg"

aws_region: "eu-west-1"
aws_account_id: "733781933474"
aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=faasm file=~/.aws/credentials') }}"
aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=faasm file=~/.aws/credentials') }}"

private_key_name: "faasm_key"
private_key_file: "~/faasm_aws_key.pem"