#pragma once

#include <iwasm/include/wasm_export.h>
#include <sgx.h>
#include <sgx_defs.h>

// This file defines the set of functions that can be called from enclave code
// to the outside (untrusted) Faasm runtime. OCalls in SGX terminology.
// TODO: should we delete this file and use the autogenerated one?
extern "C"
{
    extern sgx_status_t SGX_CDECL ocallLogError(const char* msg);

    extern sgx_status_t SGX_CDECL ocallLogDebug(const char* msg);

// In enclave release mode (i.e NDEBUG set) we disable debug logging
#ifdef FAASM_SGX_DEBUG
#define SPDLOG_DEBUG_SGX(...)                                                  \
    {                                                                          \
        const size_t __bufferSize = 512;                                       \
        char __buffer[__bufferSize];                                           \
        snprintf(__buffer, __bufferSize, __VA_ARGS__);                         \
        ocallLogDebug(__buffer);                                               \
    }
#else
#define SPDLOG_DEBUG_SGX(...) ;
#endif

#define SPDLOG_ERROR_SGX(...)                                                  \
    {                                                                          \
        const size_t __bufferSize = 512;                                       \
        char __buffer[__bufferSize];                                           \
        snprintf(__buffer, __bufferSize, __VA_ARGS__);                         \
        ocallLogError(__buffer);                                               \
    }

    extern sgx_status_t SGX_CDECL ocallFaasmReadInput(int* returnValue,
                                                      uint8_t* buffer,
                                                      unsigned int bufferSize);

    extern sgx_status_t SGX_CDECL
    ocallFaasmWriteOutput(char* output, unsigned int outputSize);

    extern sgx_status_t SGX_CDECL ocallFaasmChainName(unsigned int* returnValue,
                                                      const char* name,
                                                      const uint8_t* input,
                                                      unsigned int inputSize);

    extern sgx_status_t SGX_CDECL ocallFaasmChainPtr(unsigned int* returnValue,
                                                     const int wasmFuncPtr,
                                                     const uint8_t* input,
                                                     unsigned int inputSize);

    extern sgx_status_t SGX_CDECL ocallFaasmAwaitCall(unsigned int* returnValue,
                                                      unsigned int callId);

    extern sgx_status_t SGX_CDECL
    ocallFaasmAwaitCallOutput(unsigned int* returnValue,
                              unsigned int callId,
                              char* buffer,
                              unsigned int bufferSize);

    extern sgx_status_t SGX_CDECL ocallSbrk(int32_t* returnValue,
                                            int32_t increment);
}
