---

- name: "Tweak system parameters to help with throughput"
  become: yes
  copy:
    src: sysctl.conf
    dest: "/etc/sysctl.d/60-throughput.conf"
    mode: 0644

- name: "Apply the configuration"
  become: yes
  shell: "sysctl -p /etc/sysctl.d/60-throughput.conf"