---

- name: "Install Python system deps"
  become: yes
  apt:
    name:
      - python3-dev
      - python3-pip
      - python3-venv
      - libcairo2-dev

- name: "Update pip"
  become: yes
  shell: "pip3 install -U pip"

- name: "Install python deps"
  become: yes
  shell: "pip3 install -r faasmcli/requirements.txt"
  args:
    chdir: "/usr/local/code/faasm"

- name: "Install CLI"
  become: yes
  shell: "pip3 install -e faasmcli/"
  args:
    chdir: "/usr/local/code/faasm"
