apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: faasm-test
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: faasm/knative-worker
          env:
            - name: TARGET
              value: "  Foobar baz"