---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    s3_bucket_name: "faasm-runtime"
    sqs_queue_name: "faasm-messages"
    aws_region: "eu-west-1"
    ansible_python_interpreter: "../venv/bin/python3"
    aws_account_id: "733781933474"
    aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=faasm file=~/.aws/credentials') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=faasm file=~/.aws/credentials') }}"
    private_key_name: "faasm_key"
    private_key_file: "~/faasm_aws_key.pem"
  tasks:
    - name: "Create SQS queue"
      sqs_queue:
        name: "{{ item }}"
        region: "{{ aws_region }}"
        default_visibility_timeout: 120
      with_items:
        - "{{ sqs_queue_name }}"

    - name: "Create S3 bucket"
      s3_bucket:
        name: "{{ item }}"
        region: "{{ aws_region }}"
      with_items:
        - "{{ s3_bucket_name }}"
  roles:
    - pywren