---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "../venv/bin/python3"
  tasks:
    - name: "Create SQS queue"
      sqs_queue:
        name: "{{ sqs_queue_name }}"
        region: "{{ aws_region }}"
        default_visibility_timeout: 120

    - name: "Create S3 bucket"
      s3_bucket:
        name: "{{ s3_bucket_name }}"
        region: "{{ aws_region }}"

    - name: "Create Elasticache instance"
      elasticache:
        name: "{{ elasticache_name }}"
        region: "{{ aws_region }}"
        engine: redis
        state: present
        node_type: cache.t2.medium
        num_nodes: 1

  roles:
    - aws_roles
    - pywren