---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Clone AWS lambda CPP repo"
      git:
        repo: "https://github.com/awslabs/aws-lambda-cpp"
        dest: "/usr/local/code/aws-lambda-cpp"

    - name: "Set up build"
      shell: "mkdir -p build"
      args:
        chdir: "/usr/local/code/aws-lambda-cpp"

    # Note - CMAKE_BUILD_TYPE=Debug allows verbose logging
    - name: "Prepare build"
      shell: 'cmake -DCMAKE_BUILD_TYPE=Release -DLOG_VERBOSITY=3 -DBUILD_SHARED_LIBS=OFF ..'
      args:
        chdir: "/usr/local/code/aws-lambda-cpp/build"

    - name: "Build components"
      shell: "make"
      args:
        chdir: "/usr/local/code/aws-lambda-cpp/build"

    - name: "Install"
      become: yes
      shell: "sudo make install"
      args:
        chdir: "/usr/local/code/aws-lambda-cpp/build"
