---

- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: "Install python"
      raw: "sudo apt-get -y install python"
  roles:
    - linux
    - llvm10
    - protobuf
    - grpc
    - code
    - python
    - spdlog
    - eigen
    - cereal
    - capacity
    - pistache
    - rapidjson
    - runtime_fs
    - time
