---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Install system deps"
      become: yes
      apt:
        name:
          - qtbase5-dev

    - name: "Clone easy_profiler repo"
      git:
        repo: "git@github.com:yse/easy_profiler.git"
        dest: "/usr/local/code/lib/easy_profiler"
        version: "v2.0.1"

    - name: "Set up build"
      shell: "mkdir -p build"
      args:
        chdir: "/usr/local/code/lib/easy_profiler"

    - name: "Prepare build"
      shell: "cmake -DCMAKE_BUILD_TYPE=Release .."
      args:
        chdir: "/usr/local/code/lib/easy_profiler/build"

    - name: "Build"
      shell: "make"
      args:
        chdir: "/usr/local/code/lib/easy_profiler/build"
