---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Checkout eigen3 source"
      git:
        accept_hostkey: yes
        repo: "git@github.com:eigenteam/eigen-git-mirror.git"
        dest: "/tmp/eigen3"
        clone: yes
        update: yes
        version: "32864b0f746c4397198f325fb657327a5d2af604"

    - name: "Create build dir"
      file:
        path: "/tmp/eigen3/build"
        state: directory

    - name: "Cmake"
      shell: "cmake -DCMAKE_BUILD_TYPE=Release .."
      args:
        chdir: "/tmp/eigen3/build"

    - name: "Install"
      become: yes
      shell: "make install"
      args:
        chdir: "/tmp/eigen3/build"
