---

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: "Set up dir"
      file:
        path: "{{ ansible_env.HOME }}/faasm/firecracker"
        state: directory

    - name: "Download firecracker release binaries"
      get_url:
        url: "https://github.com/firecracker-microvm/firecracker/releases/download/v0.17.0/{{ item.full }}"
        dest: "{{ ansible_env.HOME }}/faasm/firecracker/{{ item.short }}"
      with_items:
        - { "full": "firecracker-v0.17.0", "short": "firecracker" }
        - { "full": "jailer-v0.17.0", "short": "jailer" }

    - name: "Add execute perms"
      file:
        path: "{{ ansible_env.HOME }}/faasm/firecracker/{{ item }}"
        mode: "a+x"
      with_items:
        - "firecracker"
        - "jailer"

    - name: "Download kernel and rootfs"
      get_url:
        url: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/faasm/firecracker/"
      with_items:
        - "https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin"
        - "https://s3.amazonaws.com/spec.ccfc.min/img/hello/fsfiles/hello-rootfs.ext4"

    - name: "Add read/write on /dev/kvm"
      become: yes
      shell: "setfacl -m u:{{ ansible_env.USER }}:rw /dev/kvm"
