---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Download openmpi"
        shell: "{{ item }}"
        args:
          chdir: "/tmp"
        with_items:
          - "https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz"
          - "tar -xf openmpi-4.0.2.tar.gz"

    - name: "Make and install"
      become: yes
      shell: "{{ item }}"
      args:
        chdir: "/tmp/openmpi-4.0.2"
      with_items:
        - "./configure"
        - "make"
        - "make install"
