---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "System deps for protobuf"
      become: yes
      apt:
        name:
        - autoconf
        - automake
        - libtool
        - curl
        - make
        - unzip

    - name: "Download protobuf source"
      shell: "{{ item }}"
      args:
        chdir: "/tmp/"
      with_items:
        - "curl -O -L https://github.com/google/protobuf/releases/download/v3.6.0/protobuf-cpp-3.6.0.tar.gz"
        - "tar xvf protobuf-cpp-3.6.0.tar.gz"

    - name: "Build and install"
      become: yes
      shell: "{{ item }}"
      args:
        chdir: "/tmp/protobuf-3.6.0"
      with_items:
        - "./configure --prefix=/usr CC=/usr/bin/clang CPP=/usr/bin/clang-cpp CXX=/usr/bin/clang++"
        - "make"
        - "make install"
        - "ldconfig"
