apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: faasm
spec:
  selector:
    role: edge
  type: LoadBalancer
  externalIPs:
    - 192.168.0.38   # Must match the master node
  ports:
    - port: 8001
      targetPort: 8001
