//
// Created by Joshua Heinemann on 10.06.20.
// TU-Braunschweig (heineman@ibr.cs.tu-bs.de)
//

#ifndef FAASM_SGX_FAASM_ERROR_H
#define FAASM_SGX_FAASM_ERROR_H

#define FAASM_SGX_ERROR(X) (0x00000000|(X))
typedef enum _error{
    FAASM_SGX_SUCCESS = FAASM_SGX_ERROR(0x0),
    FAASM_SGX_INVALID_PTR = FAASM_SGX_ERROR(0x1),
    FAASM_SGX_WAMR_RTE_INIT_FAILED = FAASM_SGX_ERROR(0x2),
    FAASM_SGX_WAMR_MODULE_LOAD_FAILED = FAASM_SGX_ERROR(0x3),
    FAASM_SGX_WAMR_MODULE_INSTANTIATION_FAILED = FAASM_SGX_ERROR(0x4),
    FAASM_SGX_WAMR_EXECUTION_ENVIRONMENT_GENERATION_FAILED = FAASM_SGX_ERROR(0x5),
    FAASM_SGX_WAMR_FUNCTION_NOT_FOUND = FAASM_SGX_ERROR(0x6),
    FAASM_SGX_WAMR_FUNCTION_UNABLE_TO_CALL = FAASM_SGX_ERROR(0x7),
    FAASM_SGX_SGX_NOT_AVAILABLE = FAASM_SGX_ERROR(0x8),
    FAASM_SGX_SGX_V1_LEAF_NOT_AVAILABLE = FAASM_SGX_ERROR(0x9),
    FAASM_SGX_SGX_V2_LEAF_NOT_AVAILABLE = FAASM_SGX_ERROR(0xA)
}faasm_sgx_status_t;

#endif //FAASM_SGX_FAASM_ERROR_H
