---

- name: "Check if rapidjson installed"
  stat:
    path: /usr/local/include/rapidjson
  register: rj_stat

- name: "Clone rapidjson repo"
  git:
    repo: "https://github.com/Tencent/rapidjson"
    dest: "/tmp/rapidjson"
    version: "2ce91b823c8b4504b9c40f99abf00917641cef6c"
  when: rj_stat.stat.exists == False

- name: "Set up build"
  shell: "mkdir -p build"
  args:
    chdir: "/tmp/rapidjson"
  when: rj_stat.stat.exists == False

- name: "Prepare build"
  become: yes
  shell: "{{ item }}"
  args:
    chdir: "/tmp/rapidjson/build"    
  when: rj_stat.stat.exists == False
  with_items:
    - "cmake -GNinja .."
    - "ninja"
    - "ninja install"

- name: "Clean up"
  become: yes
  file:
    state: absent
    path: "/tmp/rapidjson"
