---

- name: "Check if grpc is installed"
  stat:
    path: /usr/local/include/grpcpp/
  register: g_stat

- name: "Clone gRPC repo"
  git:
    repo: "https://github.com/grpc/grpc"
    dest: "/tmp/grpc"
    version: "v1.31.0"
  when: g_stat.stat.exists == False

- name: "Update submodules"
  shell: "git submodule update --init"
  args:
    chdir: "/tmp/grpc"
  when: g_stat.stat.exists == False

- name: "Set up build"
  shell: "mkdir -p /tmp/grpc/cmake/build"
  when: g_stat.stat.exists == False

- name: "CMake Build"
  shell: >
    cmake -GNinja \
    -DgRPC_INSTALL=ON  \
    -DgRPC_BUILD_TESTS=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 \
    -DCMAKE_C_COMPILER=/usr/bin/clang-10 \
    ../..
  args:
    chdir: "/tmp/grpc/cmake/build"
  when: g_stat.stat.exists == False

- name: "Install"
  become: yes
  shell: "ninja install"
  args:
    chdir: "/tmp/grpc/cmake/build"
  when: g_stat.stat.exists == False

- name: "Clean up"
  become: yes
  shell: "rm -rf /tmp/grpc"

