cmake_minimum_required(VERSION 3.4.0)

set(EXE_SUFFIX "")

set(CMAKE_C_COMPILER /usr/bin/clang-9)
set(CMAKE_CXX_COMPILER /usr/bin/clang++-9)
set(CMAKE_AR /usr/bin/llvm-ar-9)
set(CMAKE_NM /usr/bin/llvm-nm-9)
set(CMAKE_RANLIB /usr/bin/llvm-ranlib-9)
set(CMAKE_LD /usr/bin/wasm-ld-9)

set(FAASM_SYSROOT /usr/local/faasm/llvm-sysroot)
set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} --sysroot=${FAASM_SYSROOT})
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} --sysroot=${FAASM_SYSROOT})
set(CMAKE_SYSROOT ${FAASM_SYSROOT})

set(CMAKE_C_COMPILER_TARGET wasm32)
set(CMAKE_CXX_COMPILER_TARGET wasm32)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

